### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by lazka** [lazka/msys2-web#11]
libcrypt is in the repo but no in the interface

lzo2 is in the queue and marked as not built, but it's there.

**Comment by Alexpux** [comment]
@lazka there a lot of other packages too with the same status

**Comment by lazka** [comment]
I think this is due to https://github.com/Alexpux/MSYS2-packages/commit/a58271b39573453c79498b2e7c5da7de9d404565#diff-6852d1c1f8300eec174950c21abe30e2

I renamed the basepkg names there but the packages were never rebuilt and now the names in the repo and git don't match.

**Comment by lazka** [comment]
Things look fine to me now. Thanks for the rebuilds!
